version: "3.6"

services:
  app:
    container_name: twelve_factors
    image: paulkaufmann/twelve_factors
    build:
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:postgresql://postgres:$POSTGRES_PORT/postgres",
        "spring.datasource.username" : "$POSTGRES_USER",
        "spring.datasource.password" : "$POSTGRES_PASSWORD",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
  postgres:
    image: postgres:13.1-alpine
    container_name: postgres
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD